// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxL3Z4t6eYygkIPsD877yvonuhWsb23xU',
    appId: '1:62324189270:web:bca5dc2a4d98c564c233f7',
    messagingSenderId: '62324189270',
    projectId: 'fir-flutter-dee55',
    authDomain: 'fir-flutter-dee55.firebaseapp.com',
    storageBucket: 'fir-flutter-dee55.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZV9Hq76hji3htsctZxKhrJTSsFoGXBgc',
    appId: '1:62324189270:android:545b3a5c38f41a42c233f7',
    messagingSenderId: '62324189270',
    projectId: 'fir-flutter-dee55',
    storageBucket: 'fir-flutter-dee55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBmTcgalJA-cfKf8NHCw_-lV1Zc7mOWi8',
    appId: '1:62324189270:ios:21e968a2ad0ab988c233f7',
    messagingSenderId: '62324189270',
    projectId: 'fir-flutter-dee55',
    storageBucket: 'fir-flutter-dee55.firebasestorage.app',
    iosBundleId: 'com.example.fireFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBmTcgalJA-cfKf8NHCw_-lV1Zc7mOWi8',
    appId: '1:62324189270:ios:21e968a2ad0ab988c233f7',
    messagingSenderId: '62324189270',
    projectId: 'fir-flutter-dee55',
    storageBucket: 'fir-flutter-dee55.firebasestorage.app',
    iosBundleId: 'com.example.fireFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxL3Z4t6eYygkIPsD877yvonuhWsb23xU',
    appId: '1:62324189270:web:96eaa10095146365c233f7',
    messagingSenderId: '62324189270',
    projectId: 'fir-flutter-dee55',
    authDomain: 'fir-flutter-dee55.firebaseapp.com',
    storageBucket: 'fir-flutter-dee55.firebasestorage.app',
  );
}
