// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBufELGsiAR5V-2ikh1DVxsw41TjPZ9ayg',
    appId: '1:1015109695393:web:e86393e948fb28791cbde0',
    messagingSenderId: '1015109695393',
    projectId: 'auth-firebase-5710f',
    authDomain: 'auth-firebase-5710f.firebaseapp.com',
    storageBucket: 'auth-firebase-5710f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpJTs8lMTgjUgsKeNtFYdVBXXJYFU09KM',
    appId: '1:1015109695393:android:3e0d5bb10192380c1cbde0',
    messagingSenderId: '1015109695393',
    projectId: 'auth-firebase-5710f',
    storageBucket: 'auth-firebase-5710f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv5l0HkSoQ_FctGLi-zHIkBSpil6sYd_I',
    appId: '1:1015109695393:ios:7735fb4ce5a2ae071cbde0',
    messagingSenderId: '1015109695393',
    projectId: 'auth-firebase-5710f',
    storageBucket: 'auth-firebase-5710f.firebasestorage.app',
    iosClientId: '1015109695393-8vc2pesnjh764mmoo7edf6ce85aosp2n.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv5l0HkSoQ_FctGLi-zHIkBSpil6sYd_I',
    appId: '1:1015109695393:ios:7735fb4ce5a2ae071cbde0',
    messagingSenderId: '1015109695393',
    projectId: 'auth-firebase-5710f',
    storageBucket: 'auth-firebase-5710f.firebasestorage.app',
    iosClientId: '1015109695393-8vc2pesnjh764mmoo7edf6ce85aosp2n.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBufELGsiAR5V-2ikh1DVxsw41TjPZ9ayg',
    appId: '1:1015109695393:web:e2aa8c4ec355ecc51cbde0',
    messagingSenderId: '1015109695393',
    projectId: 'auth-firebase-5710f',
    authDomain: 'auth-firebase-5710f.firebaseapp.com',
    storageBucket: 'auth-firebase-5710f.firebasestorage.app',
  );
}
