// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNA-wn4g4bhFtoULJidtBsjD4E-a3nOF8',
    appId: '1:856982741419:web:cae24580ff806fee67b2ee',
    messagingSenderId: '856982741419',
    projectId: 'jujutsu-fire',
    authDomain: 'jujutsu-fire.firebaseapp.com',
    storageBucket: 'jujutsu-fire.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlWQ08FMsX8fRKvAmoQm-WmkHvAsfInCA',
    appId: '1:856982741419:android:4afd5c9dd1faf61567b2ee',
    messagingSenderId: '856982741419',
    projectId: 'jujutsu-fire',
    storageBucket: 'jujutsu-fire.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMTpfcCwkkVYVb6ZI6uC5Smcv_Osdf0fs',
    appId: '1:856982741419:ios:8d93df8d074f41a267b2ee',
    messagingSenderId: '856982741419',
    projectId: 'jujutsu-fire',
    storageBucket: 'jujutsu-fire.firebasestorage.app',
    iosClientId: '856982741419-nuccjqnsrkiq2l8u88u52ujcqdk3a849.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireFlutter',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMTpfcCwkkVYVb6ZI6uC5Smcv_Osdf0fs',
    appId: '1:856982741419:ios:8d93df8d074f41a267b2ee',
    messagingSenderId: '856982741419',
    projectId: 'jujutsu-fire',
    storageBucket: 'jujutsu-fire.firebasestorage.app',
    iosClientId: '856982741419-nuccjqnsrkiq2l8u88u52ujcqdk3a849.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNA-wn4g4bhFtoULJidtBsjD4E-a3nOF8',
    appId: '1:856982741419:web:5e2991242fc0f0b167b2ee',
    messagingSenderId: '856982741419',
    projectId: 'jujutsu-fire',
    authDomain: 'jujutsu-fire.firebaseapp.com',
    storageBucket: 'jujutsu-fire.firebasestorage.app',
  );
}
